export const ROOT_PRODUCT_LIST = "ROOT_PRODUCT_LIST";

export const CURRENT_PRODUCT_DETAILS = "CURRENT_PRODUCT_DETAILS";

export const SERVICE_REQUEST_LIST = "SERVICE_REQUEST_LIST";
export const CURRENT_SERVICE_REQUEST_DETAILS =
  "CURRENT_SERVICE_REQUEST_DETAILS";
